fix(task_manager.h): 首次tick超时任务没有重置
owent/libcopp pull request #46
Opened 2023-03-30 03:14 UTC by vbirds

首次tick，task_timeout_timer_里的超时任务没有重置

2023-03-30 10:53 UTC, owent commented
感谢修复，可否也修复一下单元测试和下面 C++20 协程的相同问题（1310行）？
或者仅修复一下单元测试，C++20协程的相同BUG我自己晚点来也行。
之前单元测试也是有问题的，导致没检测出来。

2023-03-30 11:41 UTC, vbirds commented
> 感谢修复，可否也修复一下单元测试和下面 C++20 协程的相同问题（1310行）？ 或者仅修复一下单元测试，C++20协程的相同BUG我自己晚点来也行。 之前单元测试也是有问题的，导致没检测出来。

提交了，韬哥帮review下代码

2023-03-30 13:45 UTC, owent requested changes

2023-03-30 13:45 UTC, owent commented on test/case/task_promise_task_manager_test.cpp
> +    next_time = cur_time + 8;
之前单元测试里tick的值是没问题的。有问题的是在第8个tick的时候不应该消耗定时器， 因为原来的 3+5=8是最后一个在有效期内的tick。而第9个tick触发超时。
这个改过之后变成了，定时器被重置为 cur_time+5超时。直接cur_time+8直接就超时了，反而没测出来这个功能。

2023-03-31 01:43 UTC, vbirds commented on test/case/task_promise_task_manager_test.cpp
> +    next_time = cur_time + 8;
我的锅，之前理解错了，马上改下

2023-03-31 02:36 UTC, vbirds commented on test/case/task_promise_task_manager_test.cpp
> +    next_time = cur_time + 8;
单元测试改了，韬哥再帮review下

2023-03-31 06:41 UTC, owent requested changes

2023-03-31 06:41 UTC, owent commented on test/case/coroutine_task_manager_test.cpp
> +  // tick reset timeout: 3 + 5 = 8
`task_mgr->tick(8);` 还是需要保留哈，这是用来确保tick(8)的时候定时器还没有执行删除的。

2023-04-03 03:24 UTC, owent approved these changes

2023-04-03 03:25 UTC, merged